name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Dependencies
      run: npm install
    - name: Build Electron App
      run: npm run package
    - name: Create zip
      run: zip -r my-app-${{ github.ref }}-${{ matrix.os }}.zip ./out
    - name: "Upload build"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev-${{ github.run_id }}-${{ github.run_attempt }}"
        prerelease: false
        title: "Build"
        files: "my-app-${{ github.ref }}-${{ matrix.os }}.zip"
